---
- name: Install dnf-automatic
  ansible.builtin.dnf:
    name: dnf-automatic
    state: present

- name: Enable and start dnf-automatic-install timer
  ansible.builtin.systemd:
    name: dnf-automatic-install.timer
    enabled: true
    state: started
