---
homelab_user:  homelab
homelab_group: homelab

homelab_xdg_config_home: "/home/{{ homelab_user }}/.config"
homelab_xdg_cache_home:  "/home/{{ homelab_user }}/.cache"
homelab_xdg_data_home:   "/home/{{ homelab_user }}/.local/share"
homelab_xdg_log_home:    "/home/{{ homelab_user }}/.local/state"

homelab_quadlet_dir:     "{{ homelab_xdg_config_home }}/containers/systemd"
homelab_environment_dir: "{{ homelab_xdg_config_home }}/environment.d"
homelab_user_dir:        "{{ homelab_xdg_config_home }}/systemd/user"

enabled_services: []

# Traefik
traefik_env:   prd
traefik_rules: []

# Pi-hole
pihole_cnames: []
pihole_upstreams:
  - 208.67.222.222
  - 208.67.220.220
  - 2620:119:35::35
  - 2620:119:53::53

# Plex
plex_advertise_ip: "https://127.0.0.1:32400/"
plex_allowed_networks:
  - 192.168.86.0/24
  - 100.64.0.0/10
  - 172.17.0.0/16
  - 172.18.0.0/16

# Prometheus exporters
openweather_city: "San Marcos, CA"
