---
- name: Configure host OS
  hosts: all
  become: true
  vars:
    ansible_user: "{{ admin_user }}"
  roles:
    - quadlet_host

- name: Install Podman Quadlets
  hosts: all
  become: true
  vars:
    ansible_user: "{{ admin_user }}"
  roles:
    - quadlets
