---
- name: System baseline
  hosts: all
  become: true
  vars:
    ansible_user: "{{ admin_user }}"
  roles:
    - system
    - restic

- name: Mail server
  hosts: mail_servers
  become: true
  vars:
    ansible_user: "{{ admin_user }}"
  roles:
    - mail

- name: Git server
  hosts: git_servers
  become: true
  vars:
    ansible_user: "{{ admin_user }}"
  roles:
    - git
