---
- name: Update all hosts
  hosts: all
  become: true
  vars:
    ansible_user: "{{ admin_user }}"
  tasks:
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
      register: dnf_result

    - name: Report updated packages
      ansible.builtin.debug:
        msg: "{{ dnf_result.results }}"
      when: dnf_result.changed
