---
all:
  children:
    workstation:
      hosts:
        laptop:
          ansible_host: localhost
          ansible_connection: local

    local:
      hosts:
        media:
          ansible_host: media.tail950f.ts.net
          ansible_connection: ssh

    remote:
      hosts:
        outpost:
          ansible_host: outpost.tail950f.ts.net
          ansible_connection: ssh
