---
all:
  children:
    workstation:
      hosts:
        laptop:
          ansible_host: localhost
          ansible_connection: local
          pihole_host_ip: 127.0.0.1
          extra_firewall_ports: []

    local:
      hosts:
        media:
          ansible_host: media.tail950f.ts.net
          ansible_connection: ssh
          pihole_host_ip: 192.168.86.10   # update to real IP
          extra_firewall_ports:
            - { port: 53,    proto: tcp }
            - { port: 53,    proto: udp }
            - { port: 1900,  proto: udp }
            - { port: 32400, proto: tcp }
            - { port: 32410, proto: udp }
            - { port: 32412, proto: udp }
            - { port: 32413, proto: udp }
            - { port: 32414, proto: udp }
            - { port: 32469, proto: tcp }
            - { port: 7359,  proto: udp }
            - { port: 8096,  proto: tcp }

    remote:
      hosts:
        outpost:
          ansible_host: outpost.tail950f.ts.net
          ansible_connection: ssh
          extra_firewall_ports: []
