set shell := ['zsh', '-c']

config_dir      := env('XDG_CONFIG_HOME', x"~/.config")
container_dir   := config_dir / 'containers/systemd'
environment_dir := config_dir / 'environment.d'
user_dir        := config_dir / 'systemd/user'

systemctl  := 'systemctl --user'
journalctl := 'journalctl --user'

services := '''fd --glob '*.container' --format '{/.}' ~/.config/containers/systemd'''

_all:

_list_services:
  @fd --glob '*.container' --format '{/.}' ~/.config/containers/systemd

# Reload Quadlet services
reload:
  {{ systemctl }} daemon-reload

# Start a Quadlet service
start service=`just _list_services | fzf`:
  {{ systemctl }} start {{ service }}

# Start all Quadlets services
start-all:
  just _list_services | xargs -I % {{ systemctl }} start %.service

# Stop a Quadlet service
stop service=`just _list_services | fzf`:
  {{ systemctl }} stop {{ service }}

# Stop all Quadlets services
stop-all:
  just _list_services | xargs -I % {{ systemctl }} stop %.service

# Restart a Quadlet service
restart service:
  {{ systemctl }} restart {{ service }}

# Restart all Quadlets services
restart-all:
  just _list_services | xargs -I % {{ systemctl }} restart %.service

# Stop, disable, and remove a service's Quadlet files
remove service=`just _list_services | fzf`:
  -{{ systemctl }} stop {{ service }}.service
  -{{ systemctl }} disable {{ service }}.service
  rm -f '{{ container_dir }}/{{ service }}.container'
  rm -f '{{ container_dir }}/{{ service }}.env'
  rm -rf '{{ container_dir }}/{{ service }}.container.d'
  {{ systemctl }} daemon-reload

# Get the status of a Quadlet service
status service=`just _list_services | fzf`:
  {{ systemctl }} status {{ service }}

# Get the logs of a Quadlet service
logs service=`just _list_services | fzf` *extra:
  {{ journalctl }} --unit {{ service }} {{ extra }}

# Print the current configuration of a Quadlet service
cat service=`just _list_services | fzf`:
  {{ systemctl }} cat {{ service }}

# Inspect a service's container
inspect service=`just _list_services | fzf`:
  podman inspect systemd-{{ service }}

# Verify a Quadlet service
verify service=`just _list_services | fzf`:
  systemd-analyze --user --generators=true verify {{ service }}.service

# Open a shell in a service container
shell service=`just _list_services | fzf` shell='/bin/sh':
  podman exec -it systemd-{{ service }} {{ shell }}

# Launch a bash shell in a fedora container on the homelab network
debug:
  podman run -it --rm --network homelab fedora bash

# Create certificates for testing services locally (e.g., localhost)
mkcert domain:
  mkdir -p ~/.config/traefik/certs
  cd ~/.config/traefik/certs && mkcert '{{ domain }}' '*.{{ domain }}'

# Initialize iSponsorBlockTV
initialize-isponsorblocktv:
  mkdir -p '{{ config_dir }}/isponsorblocktv'
  podman run -it --rm --volume '{{ config_dir }}/isponsorblocktv':/app/data:Z ghcr.io/dmunozv04/isponsorblocktv --setup-cli

# Install the Jellyfin app on a Samsung TV
install-jellyfin ip:
  podman run --rm --ulimit nofile=1024:65536 ghcr.io/georift/install-jellyfin-tizen {{ ip }}

# Stop any containers that mount the /media volume (e.g., for NAS maintenance)
stop-media:
  podman container ps --format '{{{{ .ID }}' | \
    xargs podman container inspect | \
    jq -r '.[] | { Id, Mounts } | select(.Mounts[].Source == "/media") | .Id' | \
    xargs podman container stop
