---
- name: Deploy restic password files
  ansible.builtin.copy:
    content: "{{ item.value.password }}"
    dest: "/home/{{ restic_user }}/.restic-password-{{ item.key }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0600"
  loop: "{{ restic_targets | dict2items }}"
  no_log: true

- name: Deploy restic repository files
  ansible.builtin.copy:
    content: "{{ item.value.repository }}"
    dest: "/home/{{ restic_user }}/.restic-repository-{{ item.key }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0600"
  loop: "{{ restic_targets | dict2items }}"

