---
- name: Create restic user
  ansible.builtin.import_tasks: user.yml

- name: Install restic binary
  ansible.builtin.import_tasks: binary.yml

- name: Configure SSH access
  ansible.builtin.import_tasks: ssh.yml

- name: Configure resticprofile
  ansible.builtin.import_tasks: config.yml

- name: Schedule backups
  ansible.builtin.import_tasks: schedule.yml
