---
- name: Create restic SSH directory
  ansible.builtin.file:
    path: "{{ restic_home }}/.ssh"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0700"

- name: Deploy restic SSH config
  ansible.builtin.template:
    src: ssh.conf.j2
    dest: "{{ restic_home }}/.ssh/config"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0600"

- name: Deploy restic SSH private key
  ansible.builtin.copy:
    content: "{{ restic_ssh_private_key }}"
    dest: "{{ restic_home }}/.ssh/id_rsa"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0600"
  no_log: true

- name: Deploy restic SSH public key
  ansible.builtin.copy:
    content: "{{ restic_ssh_public_key }}"
    dest: "{{ restic_home }}/.ssh/id_rsa.pub"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0600"
  no_log: true
