---
- name: Create restic group
  ansible.builtin.group:
    name: "{{ restic_group }}"
    state: present

- name: Create restic user
  ansible.builtin.user:
    name: "{{ restic_user }}"
    group: "{{ restic_group }}"
    shell: /bin/zsh
    create_home: true
    password: "!"
    state: present
  register: restic_user_info

- name: Set restic fact
  ansible.builtin.set_fact:
    restic_home: "{{ restic_user_info.home }}"
    restic_uid: "{{ restic_user_info.uid }}"

- name: Enable linger for restic user
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ restic_user }}
    creates: /var/lib/systemd/linger/{{ restic_user }}

- name: Create restic bin directory
  ansible.builtin.file:
    path: "{{ restic_home }}/bin"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0755"
