---
- name: Enable personal COPR repo
  community.general.copr:
    name: cgrau/personal
    state: enabled

- name: Enable RPM Fusion free repository
  ansible.builtin.dnf:
    name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts["distribution_major_version"] }}.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Enable RPM Fusion nonfree repository
  ansible.builtin.dnf:
    name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts["distribution_major_version"] }}.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Deploy third-party repo files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - 1password.repo
    - charm.repo
    - hashicorp.repo
    - tailscale.repo
