---
version: "3.8"

services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    restart: unless-stopped
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - calibre_config:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre.entrypoints=https
      - traefik.http.routers.calibre.rule=Host(`calibre.${DOMAIN}`)
      - traefik.http.services.calibre.loadbalancer.server.port=8083

volumes:
  calibre_config:
