---
version: "3.8"

services:
  glances:
    image: nicolargo/glances:latest-full
    restart: unless-stopped
    environment:
      - GLANCES_OPT=-w
    volumes:
      - glances_config:/glances/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /home:/mnt/home:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.glances.entrypoints=https
      - traefik.http.routers.glances.rule=Host(`glances.${DOMAIN}`)
      - traefik.http.services.glances.loadbalancer.server.port=61208
    pid: host

volumes:
  glances_config:
