---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - homepage_config:/app/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.entrypoints=https
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000

volumes:
  homepage_config:
