---
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    restart: unless-stopped
    networks:
      - default
      - homekit
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - home-assistant_config:/config
    devices: []
    labels:
      - traefik.enable=true
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_default
      - traefik.http.routers.home-assistant.entrypoints=https
      - traefik.http.routers.home-assistant.rule=Host(`home.${DOMAIN}`)
      - traefik.http.services.home-assistant.loadbalancer.server.port=8123

volumes:
  home-assistant_config:
