---
version: "3.8"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - homepage_config:/app/config
      - /home:/mnt/home:ro
      - /media:/mnt/media:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.entrypoints=https
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: home-assistant
    restart: unless-stopped
    networks:
      - homekit
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - home-assistant_config:/config
    devices: []
    labels:
      - traefik.enable=true
      - traefik.docker.network=default
      - traefik.http.routers.home-assistant.entrypoints=https
      - traefik.http.routers.home-assistant.rule=Host(`home.${DOMAIN}`)
      - traefik.http.services.home-assistant.loadbalancer.server.port=8123
    privileged: true

  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    ports:
      - 51690:51690
    networks:
      - homekit
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - homebridge_config:/homebridge
    labels:
      - traefik.enable=true
      - traefik.docker.network=default
      - traefik.http.routers.homebridge.entrypoints=https
      - traefik.http.routers.homebridge.rule=Host(`homebridge.${DOMAIN}`)
      - traefik.http.services.homebridge.loadbalancer.server.port=8581

  zwave-js-ui:
    image: zwavejs/zwave-js-ui:latest
    container_name: zwave-js-ui
    restart: unless-stopped
    environment:
      - SESSION_SECRET=${ZWAVE_SESSION_SECRET}
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - zwave-js-ui_store:/usr/src/app/store
    devices: []
    labels:
      - traefik.enable=true
      - traefik.http.routers.zwave-js-ui.entrypoints=https
      - traefik.http.routers.zwave-js-ui.rule=Host(`zwave.${DOMAIN}`)
      - traefik.http.services.zwave-js-ui.loadbalancer.server.port=8091

networks:
  homekit:
    driver: macvlan
    driver_opts:
      parent: enp0s25
    ipam:
      config:
        - subnet: 192.168.86.0/24
          gateway: 192.168.86.1

volumes:
  homepage_config:
  home-assistant_config:
  homebridge_config:
  zwave-js-ui_store:
