---
services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    ports:
      - 8096:8096/tcp
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/shm:/transcode
      - jellyfin_config:/config
      - jellyfin_cache:/cache
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

volumes:
  jellyfin_config:
  jellyfin_cache:
