---
services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # ports:
    #   - 1900:1900/udp
    #   - 3005:3005/tcp
    #   - 8324:8324/tcp
    #   - 32400:32400/tcp
    #   - 32410:32410/udp
    #   - 32412:32412/udp
    #   - 32413:32413/udp
    #   - 32414:32414/udp
    #   - 32469:32469/tcp
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/shm:/transcode
      - jellyfin_config:/config
      - jellyfin_cache:/cache
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

volumes:
  jellyfin_config:
  jellyfin_cache:
