---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mealie_data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.mealie.entrypoints=https
      - traefik.http.routers.mealie.rule=Host(`mealie.${DOMAIN}`)
      - traefik.http.services.mealie.loadbalancer.server.port=9000

volumes:
  mealie_data:
