---
services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
    volumes:
      - pihole_conf:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.entrypoints=https
      - traefik.http.routers.pihole.rule=Host(`dns.${DOMAIN}`)
      - traefik.http.services.pihole.loadbalancer.server.port=80
    dns: []

volumes:
  pihole_conf:
  pihole_dnsmasq:
