---
services:
  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    command:
      - -config.file=/etc/promtail/config.yaml
    volumes:
      - ./config/promtail.yaml:/etc/promtail/config.yaml:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
