---
services:
  prometheus-exporter-openweather:
    image: billykwooten/openweather-exporter:latest
    restart: unless-stopped
    environment:
      - OW_CITY=${OPENWEATHER_CITY}
      - OW_APIKEY=${OPENWEATHER_APIKEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
