---
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - readarr_config:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.readarr.entrypoints=https
      - traefik.http.routers.readarr.rule=Host(`readarr.${DOMAIN}`)
      - traefik.http.services.readarr.loadbalancer.server.port=8787

volumes:
  readarr_config:
