---
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sabnzbd_config:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN}`)
      - traefik.http.routers.sabnzbd.entrypoints=https
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080

volumes:
  sabnzbd_config:
