---
- name: Install packages
  ansible.builtin.import_tasks: packages.yml

- name: Create homelab user
  ansible.builtin.import_tasks: user.yml

- name: Set sysctl values
  ansible.builtin.import_tasks: sysctl.yml

- name: Open firewall ports
  ansible.builtin.import_tasks: firewall.yml

- name: Install Polkit rule
  ansible.builtin.import_tasks: polkit.yml

- name: Configure Podman
  ansible.builtin.import_tasks: podman.yml
