---
- name: Create homelab group
  ansible.builtin.group:
    name: "{{ homelab_group }}"
    state: present

- name: Create homelab user
  ansible.builtin.user:
    name: "{{ homelab_user }}"
    group: "{{ homelab_group }}"
    shell: /bin/bash
    create_home: true
    password: "!"
    state: present
  register: homelab_user_info

- name: Set homelab UID fact
  ansible.builtin.set_fact:
    homelab_uid: "{{ homelab_user_info.uid }}"
