---
- name: Install packages
  ansible.builtin.dnf:
    name:
      - git
      - just
    state: present

- name: Create git user
  ansible.builtin.user:
    name: git
    shell: /usr/bin/git-shell
    create_home: true
    password: "!"
    state: present
  register: git_user_info

- name: Set git user facts
  ansible.builtin.set_fact:
    git_home: "{{ git_user_info.home }}"

- name: Create git SSH directory
  ansible.builtin.file:
    path: "{{ git_home }}/.ssh"
    state: directory
    owner: git
    group: git
    mode: "0700"

- name: Deploy authorized keys
  ansible.posix.authorized_key:
    user: git
    key: "{{ item }}"
    path: "{{ git_home }}/.ssh/authorized_keys"
    manage_dir: false
    state: present
  loop: "{{ git_authorized_keys }}"

- name: Deploy gitconfig
  ansible.builtin.copy:
    src: gitconfig
    dest: "{{ git_home }}/.gitconfig"
    owner: git
    group: git
    mode: "0644"

- name: Deploy Justfile
  ansible.builtin.copy:
    src: Justfile
    dest: "{{ git_home }}/Justfile"
    owner: git
    group: git
    mode: "0644"

- name: Create repos directory
  ansible.builtin.file:
    path: "{{ git_home }}/repos"
    state: directory
    owner: git
    group: git
    mode: "0755"
