---
- name: Deploy main.cf
  ansible.builtin.copy:
    src: main.cf
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: "0644"
  notify: Reload postfix

- name: Deploy virtual alias map
  ansible.builtin.copy:
    src: virtual
    dest: /etc/postfix/virtual
    owner: root
    group: root
    mode: "0644"
  notify: Rebuild virtual map

- name: Deploy HELO access map
  ansible.builtin.copy:
    src: helo_access
    dest: /etc/postfix/helo_access
    owner: root
    group: root
    mode: "0644"
  notify: Rebuild helo_access map

- name: Open SMTP port
  ansible.posix.firewalld:
    port: 25/tcp
    permanent: true
    state: enabled
    immediate: true
