---
domain:         localhost
traefik_config: traefik-dev.yaml
traefik_rules:  [local-tls.yaml]

restic_backup_paths:
  - path: /etc
  - path: /home/cgrau
    excludes:
      - /home/cgrau/Pictures
      - /home/cgrau/Videos
  - path: /home/cgrau/Pictures
  - path: /home/cgrau/Videos

enabled_services: []
