---
domain:         localhost
traefik_config: traefik-dev.yaml
traefik_rules:  [local-tls.yaml]

restic_backup_paths:
  - path: /etc
  - path: /home/cgrau
    excludes:
      - /home/cgrau/Pictures
      - /home/cgrau/Videos
  - path: /home/cgrau/Pictures
  - path: /home/cgrau/Videos

enabled_services:
  - calibre
  - glances
  - grafana
  - home-assistant
  - homebridge
  - homepage
  - isponsorblocktv
  - jellyfin
  - lidarr
  - loki
  - mealie
  - pihole
  - plex
  - prometheus
  - prometheus-exporter-nws
  - prometheus-exporter-openweather
  - prometheus-exporter-solaredge
  - prowlarr
  - radarr
  - sabnzbd
  - sonarr
  - traefik
  - tududi
  - whoami
  - zwave-js-ui
